"""initial rebuild

Revision ID: 71433c3d84af
Revises: 
Create Date: 2019-07-04 13:52:55.018645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71433c3d84af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_name', sa.String(length=120), nullable=True),
    sa.Column('proj_title', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_proj_title'), 'project', ['proj_title'], unique=True)
    op.create_index(op.f('ix_project_unit_name'), 'project', ['unit_name'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('rfi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rfi_number', sa.String(length=4), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('date_received', sa.String(length=40), nullable=True),
    sa.Column('date_response', sa.String(length=40), nullable=True),
    sa.Column('dwg_refer', sa.String(length=60), nullable=True),
    sa.Column('spec_refer', sa.String(length=120), nullable=True),
    sa.Column('assigned_to', sa.String(length=60), nullable=True),
    sa.Column('cost_change', sa.Boolean(), nullable=True),
    sa.Column('time_change', sa.Boolean(), nullable=True),
    sa.Column('response', sa.Text(length=400), nullable=True),
    sa.Column('reviewer', sa.String(length=60), nullable=True),
    sa.Column('filename', sa.String(length=100), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('response_fname', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfi_assigned_to'), 'rfi', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_rfi_date_received'), 'rfi', ['date_received'], unique=False)
    op.create_index(op.f('ix_rfi_date_response'), 'rfi', ['date_response'], unique=False)
    op.create_index(op.f('ix_rfi_dwg_refer'), 'rfi', ['dwg_refer'], unique=False)
    op.create_index(op.f('ix_rfi_rfi_number'), 'rfi', ['rfi_number'], unique=False)
    op.create_index(op.f('ix_rfi_spec_refer'), 'rfi', ['spec_refer'], unique=False)
    op.create_index(op.f('ix_rfi_title'), 'rfi', ['title'], unique=False)
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=60), nullable=True),
    sa.Column('firstname', sa.String(length=30), nullable=True),
    sa.Column('lastname', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_email'), 'team', ['email'], unique=True)
    op.create_index(op.f('ix_team_firstname'), 'team', ['firstname'], unique=False)
    op.create_index(op.f('ix_team_lastname'), 'team', ['lastname'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_lastname'), table_name='team')
    op.drop_index(op.f('ix_team_firstname'), table_name='team')
    op.drop_index(op.f('ix_team_email'), table_name='team')
    op.drop_table('team')
    op.drop_index(op.f('ix_rfi_title'), table_name='rfi')
    op.drop_index(op.f('ix_rfi_spec_refer'), table_name='rfi')
    op.drop_index(op.f('ix_rfi_rfi_number'), table_name='rfi')
    op.drop_index(op.f('ix_rfi_dwg_refer'), table_name='rfi')
    op.drop_index(op.f('ix_rfi_date_response'), table_name='rfi')
    op.drop_index(op.f('ix_rfi_date_received'), table_name='rfi')
    op.drop_index(op.f('ix_rfi_assigned_to'), table_name='rfi')
    op.drop_table('rfi')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_project_unit_name'), table_name='project')
    op.drop_index(op.f('ix_project_proj_title'), table_name='project')
    op.drop_table('project')
    # ### end Alembic commands ###
